name: Unity Build

on:
  push:
    branches:
      - main
      - develop
    
concurrency:
  group: unity-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Windows
    runs-on:
      - self-hosted
      - windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          clean: false  

      - name: Build Unity
        shell: cmd
        run: '"C:\Program Files\Unity\Hub\Editor\6000.4.11f1\Editor\Unity.exe" -batchmode -quit -projectPath "%GITHUB_WORKSPACE%\Mortier FU" -executeMethod BuildScript.BuildWindows -logFile -'
        
      - name: Build Unity
        shell: cmd
        run: '"C:\Program Files\Unity\Hub\Editor\6000.4.11f1\Editor\Unity.exe" -batchmode -quit -projectPath "%GITHUB_WORKSPACE%\Mortier FU" -executeMethod BuildScript.BuildLinux -logFile -'

	- name: Upload Builds
	  uses: actions/upload-artifact@v4
	  with:
	    name: Builds
	    path: Build/